version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - my_docker
networks:
  my_docker:
    external: true